<?php
namespace App\Services;
use App\Models\Employee; use App\Models\PublicHoliday; use App\Models\UnpaidAbsence; use App\Support\Money; use Brick\Math\BigDecimal; use Brick\Math\RoundingMode; use Carbon\Carbon; use Carbon\CarbonInterface; use Carbon\CarbonPeriod; use Illuminate\Support\Facades\DB; use RuntimeException;
class AbsenceService
{
public function __construct(private SalaryHistoryService $salaries){}
public function create(Employee $employee,string $type,Carbon $start,Carbon $end,?string $reason=null):UnpaidAbsence{if($end->lt($start))throw new RuntimeException('Absence end date cannot be before start date.');$overlap=UnpaidAbsence::where('employee_id',$employee->id)->whereIn('status',['pending','approved'])->whereDate('start_date','<=',$end)->whereDate('end_date','>=',$start)->exists();if($overlap)throw new RuntimeException(__('payroll.error_absence_overlap'));return UnpaidAbsence::create(['employee_id'=>$employee->id,'type'=>$type,'start_date'=>$start,'end_date'=>$end,'status'=>'pending','reason'=>$reason]);}
public function approve(UnpaidAbsence $a,int $approverId,array $settings):UnpaidAbsence{return DB::transaction(function()use($a,$approverId,$settings){$a->refresh();if($a->status!=='pending')throw new RuntimeException(__('payroll.error_absence_pending_only'));$days=$this->chargeableDays($a->start_date,$a->end_date,$settings);if($days<=0)throw new RuntimeException(__('payroll.error_absence_no_days'));$a->update(['days'=>(string)$days,'status'=>'approved','approver_id'=>$approverId,'approved_at'=>now()]);return $a->refresh();});}
public function reject(UnpaidAbsence $a,int $approverId):UnpaidAbsence{if($a->status!=='pending')throw new RuntimeException(__('payroll.error_absence_pending_only'));$a->update(['status'=>'rejected','approver_id'=>$approverId]);return $a->refresh();}
public function deductionForPeriod(Employee $employee,CarbonInterface $start,CarbonInterface $end,array $settings):array{$div=Money::d((string)($settings['salary_daily_divisor']??'0'));if($div->isLessThanOrEqualTo(0))throw new RuntimeException('salary_daily_divisor must be greater than zero.');$total=BigDecimal::zero();$details=[];$rows=UnpaidAbsence::where('employee_id',$employee->id)->where('status','approved')->whereDate('start_date','<=',$end)->whereDate('end_date','>=',$start)->get();foreach($rows as $row){$from=$row->start_date->gt($start)?$row->start_date:Carbon::instance($start->toDateTime());$to=$row->end_date->lt($end)?$row->end_date:Carbon::instance($end->toDateTime());foreach(CarbonPeriod::create($from,$to) as $date){if(!$this->isChargeableDay($date,$settings))continue;$salary=$this->salaries->salaryAt($employee,$date);$daily=$salary->dividedBy($div,12,RoundingMode::HALF_UP);$total=$total->plus($daily);$details[]=['absence_id'=>$row->id,'type'=>$row->type,'date'=>$date->toDateString(),'days'=>1,'monthly_salary_jod'=>Money::round($salary),'daily_rate_jod'=>Money::round($daily),'amount_jod'=>Money::round($daily)];}}return['total'=>$total,'details'=>$details];}
public function chargeableDays(CarbonInterface $start,CarbonInterface $end,array $settings):int{$days=0;foreach(CarbonPeriod::create($start,$end) as $date)if($this->isChargeableDay($date,$settings))$days++;return $days;}
private function isChargeableDay(CarbonInterface $date,array $settings):bool{$rest=array_map('intval',$settings['weekly_rest_days']??[5]);if(in_array($date->dayOfWeekIso,$rest,true))return false;return !PublicHoliday::whereDate('date',$date)->exists();}
}
