<?php
namespace App\Services;
use App\Models\GlAccountMapping; use App\Models\PayrollRun; use App\Support\Money; use Brick\Math\BigDecimal; use RuntimeException;
class GlExportService
{
public const REQUIRED=['payroll_expense','employer_ssc_expense','salaries_payable','ssc_payable','income_tax_payable','surcharge_payable','deductions_payable','employee_loans_receivable'];
public function lines(PayrollRun $run):array{if(!$run->isLocked()||!in_array($run->status,['approved','completed'],true))throw new RuntimeException('GL export requires an approved locked payroll.');$m=GlAccountMapping::whereIn('key',self::REQUIRED)->get()->keyBy('key');foreach(self::REQUIRED as $key)if(!$m->has($key))throw new RuntimeException("Missing GL mapping: {$key}");$run->loadMissing('payslips.employee.branch','payslips.employee.department','payslips.employee.costCenter');$lines=[];foreach($run->payslips as $p){$s=$p->calculation_snapshot??[];$org=$s['organization']??['branch_code'=>$p->employee->branch?->code,'department_code'=>$p->employee->department?->code,'cost_center_code'=>$p->employee->costCenter?->code];$expense=Money::d((string)$p->gross_salary)->minus((string)$p->unpaid_absence_deduction)->plus((string)$p->overtime_pay)->plus((string)$p->earnings_total)->plus((string)$p->adjustment_earnings_total);$this->add($lines,$m['payroll_expense'],$expense,'debit',$p->employee_id,$org);$this->add($lines,$m['employer_ssc_expense'],Money::d((string)$p->ssc_employer),'debit',$p->employee_id,$org);$this->add($lines,$m['salaries_payable'],Money::d((string)$p->net_salary),'credit',$p->employee_id,$org);$this->add($lines,$m['ssc_payable'],Money::d((string)$p->ssc_employee)->plus((string)$p->ssc_employer),'credit',$p->employee_id,$org);$this->add($lines,$m['income_tax_payable'],Money::d((string)$p->income_tax),'credit',$p->employee_id,$org);$this->add($lines,$m['surcharge_payable'],Money::d((string)$p->surcharge),'credit',$p->employee_id,$org);$this->add($lines,$m['deductions_payable'],Money::d((string)$p->deductions_total)->plus((string)$p->adjustment_deductions_total),'credit',$p->employee_id,$org);$this->add($lines,$m['employee_loans_receivable'],Money::d((string)$p->loan_deductions_total),'credit',$p->employee_id,$org);} $debit=BigDecimal::zero();$credit=BigDecimal::zero();foreach($lines as $line){$debit=$debit->plus($line['debit_jod']);$credit=$credit->plus($line['credit_jod']);}if(!$debit->isEqualTo($credit))throw new RuntimeException('Generated payroll journal is not balanced.');return['lines'=>$lines,'total_debit'=>Money::round($debit),'total_credit'=>Money::round($credit)];}
public function csv(PayrollRun $run):string{$journal=$this->lines($run);$h=fopen('php://temp','w+');fwrite($h,"\xEF\xBB\xBF");fputcsv($h,['period','employee_id','account_code','account_name','debit_jod','credit_jod','branch_code','department_code','cost_center_code']);foreach($journal['lines'] as $l)fputcsv($h,[sprintf('%02d/%04d',$run->month,$run->year),$l['employee_id'],$l['account_code'],$this->safe($l['account_name']),$l['debit_jod'],$l['credit_jod'],$l['branch_code'],$l['department_code'],$l['cost_center_code']]);rewind($h);$csv=stream_get_contents($h);fclose($h);return $csv;}
private function add(array &$lines,$mapping,BigDecimal $amount,string $side,int $employeeId,array $org):void{if($amount->isZero())return;$lines[]=['employee_id'=>$employeeId,'account_code'=>$mapping->account_code,'account_name'=>$mapping->account_name,'debit_jod'=>$side==='debit'?Money::round($amount):'0.000','credit_jod'=>$side==='credit'?Money::round($amount):'0.000','branch_code'=>$org['branch_code']??null,'department_code'=>$org['department_code']??null,'cost_center_code'=>$org['cost_center_code']??null];}
private function safe(string $v):string{return preg_match('/^[=+\-@]/u',$v)?"'".$v:$v;}
}
