<?php
namespace App\Services;
use App\Models\PayrollRun; use App\Support\Money; use RuntimeException;
class JordanFilingReportService
{
public function taxA2Csv(PayrollRun $run):string{$this->assertLocked($run);$run->loadMissing('payslips.employee');$h=fopen('php://temp','w+');fwrite($h,"\xEF\xBB\xBF");fputcsv($h,['tax_number','period','employee_full_name','national_or_ssc_number','gross_salary_paid_jod','income_tax_withheld_jod','national_contribution_withheld_jod']);foreach($run->payslips as $p){$s=$p->calculation_snapshot??[];$gross=Money::d((string)$p->gross_salary)->minus((string)$p->unpaid_absence_deduction)->plus((string)$p->overtime_pay)->plus((string)$p->earnings_total)->plus((string)$p->adjustment_earnings_total);fputcsv($h,[$this->safe((string)(tenant()->tax_number??'')),sprintf('%02d/%04d',$run->month,$run->year),$this->safe($p->employee->name),$this->safe((string)($p->employee->national_id?:$p->employee->ssc_number)),Money::round($gross),$p->income_tax,$p->surcharge]);}rewind($h);$csv=stream_get_contents($h);fclose($h);return $csv;}
public function sscCsv(PayrollRun $run):string{$this->assertLocked($run);if(blank(tenant()->ssc_establishment_number))throw new RuntimeException('SSC establishment number is required in company settings.');$run->loadMissing('payslips.employee');$h=fopen('php://temp','w+');fwrite($h,"\xEF\xBB\xBF");fputcsv($h,['ssc_establishment_number','period','employee_name','national_id','ssc_number','ssc_contribution_base_jod','employee_ssc_jod','employer_ssc_jod','total_ssc_jod']);foreach($run->payslips as $p){$snapshot=$p->calculation_snapshot??[];$base=(string)($snapshot['ssc_base']??$p->gross_salary);$total=Money::d((string)$p->ssc_employee)->plus((string)$p->ssc_employer);fputcsv($h,[$this->safe((string)tenant()->ssc_establishment_number),sprintf('%02d/%04d',$run->month,$run->year),$this->safe($p->employee->name),$this->safe((string)$p->employee->national_id),$this->safe((string)$p->employee->ssc_number),$base,$p->ssc_employee,$p->ssc_employer,Money::round($total)]);}rewind($h);$csv=stream_get_contents($h);fclose($h);return $csv;}
private function assertLocked(PayrollRun $run):void{if(!$run->isLocked()||!in_array($run->status,['approved','completed'],true))throw new RuntimeException('Government filing reports require an approved locked payroll.');}
private function safe(string $v):string{return preg_match('/^[=+\-@]/u',$v)?"'".$v:$v;}
}
