<?php
namespace App\Services;
use App\Models\Employee; use App\Models\ImportBatch; use App\Models\PayrollAdjustment; use App\Models\PayrollRun; use App\Support\Money; use Illuminate\Support\Facades\DB; use RuntimeException; use Throwable;
class PayrollAdjustmentImportService
{
public function import(array $rows,string $fileName,int $userId):ImportBatch{$batch=ImportBatch::create(['kind'=>'payroll_adjustments','file_name'=>$fileName,'status'=>'processing','total_rows'=>count($rows),'created_by'=>$userId]);$ok=0;$errors=[];foreach($rows as $i=>$row){try{DB::transaction(fn()=>$this->row($row,$userId));$ok++;}catch(Throwable $e){$errors[]=['row'=>$i+2,'message'=>$e->getMessage()];}}$failed=count($errors);$batch->update(['status'=>$failed===0?'completed':($ok===0?'failed':'partial'),'succeeded_rows'=>$ok,'failed_rows'=>$failed,'errors'=>$errors?:null,'completed_at'=>now()]);return $batch->refresh();}
private function row(array $r,int $userId):void{foreach(['national_id','kind','name','amount','payment_month','payment_year'] as $k)if(blank($r[$k]??null))throw new RuntimeException("Missing required column: {$k}");$employee=Employee::where('national_id',trim((string)$r['national_id']))->first();if(!$employee)throw new RuntimeException('Employee not found: '.$r['national_id']);$kind=strtolower(trim((string)$r['kind']));if(!in_array($kind,['earning','deduction'],true))throw new RuntimeException('kind must be earning or deduction.');$month=(int)$r['payment_month'];$year=(int)$r['payment_year'];if($month<1||$month>12)throw new RuntimeException('Invalid payment_month.');if(PayrollRun::where('month',$month)->where('year',$year)->whereIn('status',['approved','completed'])->exists())throw new RuntimeException('Payment period is already locked; choose a future payroll period.');PayrollAdjustment::create(['employee_id'=>$employee->id,'kind'=>$kind,'name'=>trim((string)$r['name']),'amount'=>Money::round(Money::d((string)$r['amount'])),'payment_month'=>$month,'payment_year'=>$year,'source_month'=>$this->intOrNull($r['source_month']??null),'source_year'=>$this->intOrNull($r['source_year']??null),'taxable'=>$this->bool($r['taxable']??($kind==='earning')),'ssc_applicable'=>$this->bool($r['ssc_applicable']??false),'reduces_taxable_income'=>$this->bool($r['reduces_taxable_income']??false),'reduces_ssc_base'=>$this->bool($r['reduces_ssc_base']??false),'status'=>'pending','reason'=>$this->nullable($r['reason']??null),'created_by'=>$userId]);}
private function bool(mixed $v):bool{return in_array(strtolower(trim((string)$v)),['1','true','yes','y'],true);}private function intOrNull(mixed $v):?int{return blank($v)?null:(int)$v;}private function nullable(mixed $v):?string{$v=trim((string)$v);return $v===''?null:$v;}
}
