<?php
namespace App\Services;
use App\Models\Employee; use App\Models\PayrollRun; use Carbon\Carbon; use Illuminate\Database\Eloquent\Builder; use Illuminate\Support\Facades\DB; use RuntimeException;
class PayrollRunService
{
public function __construct(private PayrollEngine $engine,private ComplianceSettingsService $compliance,private LoanService $loans){}
public function createRun(int $month,int $year,int $userId):PayrollRun{return DB::transaction(function()use($month,$year,$userId){if(PayrollRun::where('month',$month)->where('year',$year)->exists())throw new RuntimeException(__('hr.error_payroll_exists'));$setting=$this->compliance->forDate(Carbon::create($year,$month,1)->endOfMonth());return PayrollRun::create(['month'=>$month,'year'=>$year,'status'=>'draft','compliance_setting_id'=>$setting->id,'created_by'=>$userId]);});}
public function process(PayrollRun $run):PayrollRun{if($run->status==='completed')return $run;if($run->status!=='draft')throw new RuntimeException(__('hr.error_payroll_draft_only'));DB::transaction(function()use($run){$run->update(['status'=>'processing']);$run->loadMissing('complianceSetting');$start=Carbon::create($run->year,$run->month,1)->startOfMonth();$end=$start->copy()->endOfMonth();Employee::query()->whereDate('hire_date','<=',$end)->where(function(Builder $q)use($start,$end){$q->whereIn('status',['active','on_leave'])->orWhereHas('terminations',fn(Builder $t)=>$t->whereBetween('termination_date',[$start->toDateString(),$end->toDateString()]));})->orderBy('id')->cursor()->each(function(Employee $e)use($run){$c=$this->engine->calculate($e,$run->month,$run->year,$run->complianceSetting);$p=$run->payslips()->updateOrCreate(['employee_id'=>$e->id],['contract_salary'=>$c['contract_salary'],'gross_salary'=>$c['gross_salary'],'proration_adjustment'=>$c['proration_adjustment'],'overtime_pay'=>$c['overtime_pay'],'earnings_total'=>$c['earnings_total'],'deductions_total'=>$c['deductions_total'],'loan_deductions_total'=>$c['loan_deductions_total'],'unpaid_absence_deduction'=>$c['unpaid_absence_deduction'],'ssc_employee'=>$c['ssc_employee'],'ssc_employer'=>$c['ssc_employer'],'income_tax'=>$c['income_tax'],'surcharge'=>$c['surcharge'],'net_salary'=>$c['net_salary'],'calculation_snapshot'=>$c['snapshot']]);$this->loans->recordRepayments($p,$c['loan_repayments']);});$run->update(['status'=>'completed','completed_at'=>now()]);});return $run->refresh();}
}
