<?php
namespace App\Services;
use App\Models\ComplianceSetting; use App\Models\Employee; use App\Models\EmployeeDeduction; use App\Models\EmployeeEarning; use App\Models\OvertimeEntry; use App\Support\Money; use Brick\Math\BigDecimal; use Brick\Math\RoundingMode; use Carbon\Carbon; use RuntimeException;
class PayrollEngine
{
public function __construct(private ComplianceSettingsService $compliance,private SscCalculator $ssc,private ProgressiveTaxCalculator $taxCalculator,private LoanService $loans,private AbsenceService $absences){}
public function calculate(Employee $employee,int $month,int $year,?ComplianceSetting $setting=null): array
{
$periodStart=Carbon::create($year,$month,1)->startOfMonth();$periodEnd=$periodStart->copy()->endOfMonth();$record=$setting?:$this->compliance->forDate($periodEnd);$settings=$record->settings;$this->compliance->require($settings,['ssc_employee_percent','ssc_employer_percent','ssc_enrollment_cutoff_date','ssc_ceiling_pre_cutoff_jod','ssc_ceiling_post_cutoff_jod','income_tax_brackets','personal_exemption_annual_jod','high_earner_surcharge_threshold_annual_jod','high_earner_surcharge_percent','overtime_multiplier_standard','overtime_multiplier_rest_holiday','monthly_hours_divisor','salary_daily_divisor']);
$baseSalary=Money::d($employee->salary);$earning=$this->earningsForPeriod($employee,$periodStart,$periodEnd);$deduction=$this->deductionsForPeriod($employee,$periodStart,$periodEnd);$loan=$this->loans->dueForPeriod($employee,$periodStart,$periodEnd);$absence=$this->absences->deductionForPeriod($employee,$periodStart,$periodEnd,$baseSalary,$settings);$earnedBase=$baseSalary->minus($absence['total']);if($earnedBase->isLessThan(0))$earnedBase=BigDecimal::zero();
$sscBase=$earnedBase->plus($earning['ssc_applicable'])->minus($deduction['ssc_base_reduction']);if($sscBase->isLessThan(0))$sscBase=BigDecimal::zero();$ssc=$this->ssc->calculate($sscBase,$employee->ssc_enrollment_date,$settings);$overtimeCalc=$this->overtimePay($employee,$month,$year,$baseSalary);$overtime=$overtimeCalc['total'];
$monthlyTaxable=$earnedBase->plus($overtime)->plus($earning['taxable'])->minus($ssc['employee'])->minus($deduction['taxable_reduction']);if($monthlyTaxable->isLessThan(0))$monthlyTaxable=BigDecimal::zero();$annualIncome=$earnedBase->plus($overtime)->plus($earning['taxable'])->multipliedBy('12');$annualTaxable=$monthlyTaxable->multipliedBy('12')->minus((string)$settings['personal_exemption_annual_jod']);if($annualTaxable->isLessThan(0))$annualTaxable=BigDecimal::zero();$annualTax=$this->taxCalculator->calculate($annualTaxable,$settings['income_tax_brackets']);$annualSurcharge=BigDecimal::zero();$threshold=Money::d((string)$settings['high_earner_surcharge_threshold_annual_jod']);if($annualIncome->isGreaterThan($threshold))$annualSurcharge=Money::percent($annualIncome->minus($threshold),(string)$settings['high_earner_surcharge_percent']);$incomeTax=$annualTax->dividedBy('12',12,RoundingMode::HALF_UP);$surcharge=$annualSurcharge->dividedBy('12',12,RoundingMode::HALF_UP);
$net=$earnedBase->plus($overtime)->plus($earning['total'])->minus($deduction['total'])->minus($loan['total'])->minus($ssc['employee'])->minus($incomeTax)->minus($surcharge);
return ['gross_salary'=>Money::round($baseSalary),'overtime_pay'=>Money::round($overtime),'earnings_total'=>Money::round($earning['total']),'deductions_total'=>Money::round($deduction['total']),'loan_deductions_total'=>Money::round($loan['total']),'unpaid_absence_deduction'=>Money::round($absence['total']),'ssc_employee'=>Money::round($ssc['employee']),'ssc_employer'=>Money::round($ssc['employer']),'income_tax'=>Money::round($incomeTax),'surcharge'=>Money::round($surcharge),'net_salary'=>Money::round($net),'compliance_setting_id'=>$record->id,'loan_repayments'=>$loan['details'],'snapshot'=>['setting_version'=>$record->version_label,'effective_date'=>$record->effective_date->toDateString(),'settings'=>$settings,'base_salary'=>Money::round($baseSalary),'earned_base_salary'=>Money::round($earnedBase),'unpaid_absence_deduction'=>Money::round($absence['total']),'unpaid_absence_details'=>$absence['details'],'earnings_total'=>Money::round($earning['total']),'earnings_details'=>$earning['details'],'deductions_total'=>Money::round($deduction['total']),'deduction_details'=>$deduction['details'],'loan_deductions_total'=>Money::round($loan['total']),'loan_repayment_details'=>$loan['details'],'ssc_ceiling_used'=>Money::round($ssc['ceiling']),'ssc_base'=>Money::round($ssc['base']),'pre_cutoff_enrollment'=>$ssc['pre_cutoff'],'annual_income'=>Money::round($annualIncome),'annual_taxable'=>Money::round($annualTaxable),'overtime_details'=>$overtimeCalc['details']]];
}
private function earningsForPeriod(Employee $employee,Carbon $start,Carbon $end): array{$rows=EmployeeEarning::where('employee_id',$employee->id)->applicableTo($start,$end)->orderBy('category')->orderBy('id')->get();$total=BigDecimal::zero();$taxable=BigDecimal::zero();$ssc=BigDecimal::zero();$details=[];foreach($rows as $e){$a=Money::d($e->amount);$total=$total->plus($a);if($e->taxable)$taxable=$taxable->plus($a);if($e->ssc_applicable)$ssc=$ssc->plus($a);$details[]=['earning_id'=>$e->id,'category'=>$e->category,'name'=>$e->name,'amount_jod'=>Money::round($a),'taxable'=>$e->taxable,'ssc_applicable'=>$e->ssc_applicable,'recurring'=>$e->recurring];}return['total'=>$total,'taxable'=>$taxable,'ssc_applicable'=>$ssc,'details'=>$details];}
private function deductionsForPeriod(Employee $employee,Carbon $start,Carbon $end): array{$rows=EmployeeDeduction::where('employee_id',$employee->id)->applicableTo($start,$end)->orderBy('category')->orderBy('id')->get();$total=BigDecimal::zero();$tax=BigDecimal::zero();$ssc=BigDecimal::zero();$details=[];foreach($rows as $d){$a=Money::d($d->amount);$total=$total->plus($a);if($d->reduces_taxable_income)$tax=$tax->plus($a);if($d->reduces_ssc_base)$ssc=$ssc->plus($a);$details[]=['deduction_id'=>$d->id,'category'=>$d->category,'name'=>$d->name,'amount_jod'=>Money::round($a),'reduces_taxable_income'=>$d->reduces_taxable_income,'reduces_ssc_base'=>$d->reduces_ssc_base,'recurring'=>$d->recurring];}return['total'=>$total,'taxable_reduction'=>$tax,'ssc_base_reduction'=>$ssc,'details'=>$details];}
private function overtimePay(Employee $employee,int $month,int $year,BigDecimal $gross): array{$entries=OvertimeEntry::where('employee_id',$employee->id)->where('status','approved')->whereYear('date',$year)->whereMonth('date',$month)->orderBy('date')->get();$total=BigDecimal::zero();$details=[];$cache=[];foreach($entries as $entry){$keyDate=$entry->date->toDateString();if(!isset($cache[$keyDate])){$r=$this->compliance->forDate($entry->date);$this->compliance->require($r->settings,['monthly_hours_divisor','overtime_multiplier_standard','overtime_multiplier_rest_holiday']);$cache[$keyDate]=$r;}$r=$cache[$keyDate];$s=$r->settings;$div=Money::d((string)$s['monthly_hours_divisor']);if($div->isZero()||$div->isNegative())throw new RuntimeException('monthly_hours_divisor must be greater than zero.');$hourly=$gross->dividedBy($div,12,RoundingMode::HALF_UP);$mult=(string)$s[$entry->rate_type==='rest_holiday'?'overtime_multiplier_rest_holiday':'overtime_multiplier_standard'];$pay=$hourly->multipliedBy((string)$entry->hours)->multipliedBy($mult);$total=$total->plus($pay);$details[]=['entry_id'=>$entry->id,'date'=>$keyDate,'hours'=>(string)$entry->hours,'rate_type'=>$entry->rate_type,'multiplier'=>$mult,'monthly_hours_divisor'=>(string)$s['monthly_hours_divisor'],'settings_version'=>$r->version_label,'amount_jod'=>Money::round($pay)];}return['total'=>$total,'details'=>$details];}
}
