<?php
namespace App\Services;
use App\Models\Employee; use App\Models\PayrollAdjustment; use App\Models\PayrollRun; use App\Models\Payslip; use App\Support\Money; use Brick\Math\BigDecimal; use Illuminate\Support\Facades\DB; use RuntimeException;
class PayrollAdjustmentService
{
public function approve(PayrollAdjustment $a,int $approverId):PayrollAdjustment{if($a->status!=='pending')throw new RuntimeException(__('payroll.adjustment_pending_only'));if($a->target_payroll_run_id){$run=$a->targetPayrollRun;if(!$run||!$run->isOffCycle()||$run->status!=='draft')throw new RuntimeException('Target off-cycle payroll must still be draft.');if($a->taxable||$a->ssc_applicable||$a->reduces_taxable_income||$a->reduces_ssc_base)throw new RuntimeException('Taxable or SSC-affecting adjustments must be processed in regular payroll.');}$a->update(['status'=>'approved','approved_by'=>$approverId,'approved_at'=>now()]);return $a->refresh();}
public function void(PayrollAdjustment $a):PayrollAdjustment{if($a->status==='applied')throw new RuntimeException(__('payroll.adjustment_applied_locked'));$a->update(['status'=>'void']);return $a->refresh();}
public function forPayroll(Employee $employee,int $month,int $year):array{return $this->summarize(PayrollAdjustment::query()->where('employee_id',$employee->id)->where('payment_month',$month)->where('payment_year',$year)->whereNull('target_payroll_run_id')->where('status','approved')->whereNull('applied_payroll_run_id')->orderBy('id')->get());}
public function forTargetRun(Employee $employee,PayrollRun $run):array{if(!$run->isOffCycle())throw new RuntimeException('Targeted adjustments are only valid for off-cycle payroll.');$rows=PayrollAdjustment::query()->where('employee_id',$employee->id)->where('target_payroll_run_id',$run->id)->where('status','approved')->whereNull('applied_payroll_run_id')->orderBy('id')->get();foreach($rows as $row)if($row->taxable||$row->ssc_applicable||$row->reduces_taxable_income||$row->reduces_ssc_base)throw new RuntimeException('Taxable or SSC-affecting adjustments must be processed in regular payroll.');return $this->summarize($rows);}
private function summarize($rows):array{$earning=BigDecimal::zero();$deduction=BigDecimal::zero();$tax=BigDecimal::zero();$ssc=BigDecimal::zero();$taxReduction=BigDecimal::zero();$sscReduction=BigDecimal::zero();$details=[];foreach($rows as $row){$amount=Money::d($row->amount);if($row->kind==='earning'){$earning=$earning->plus($amount);if($row->taxable)$tax=$tax->plus($amount);if($row->ssc_applicable)$ssc=$ssc->plus($amount);}else{$deduction=$deduction->plus($amount);if($row->reduces_taxable_income)$taxReduction=$taxReduction->plus($amount);if($row->reduces_ssc_base)$sscReduction=$sscReduction->plus($amount);}$details[]=['adjustment_id'=>$row->id,'kind'=>$row->kind,'name'=>$row->name,'amount_jod'=>Money::round($amount),'source_period'=>$row->source_month&&$row->source_year?sprintf('%02d/%04d',$row->source_month,$row->source_year):null,'reason'=>$row->reason,'taxable'=>$row->taxable,'ssc_applicable'=>$row->ssc_applicable,'reduces_taxable_income'=>$row->reduces_taxable_income,'reduces_ssc_base'=>$row->reduces_ssc_base];}return['earning_total'=>$earning,'deduction_total'=>$deduction,'taxable_earnings'=>$tax,'ssc_earnings'=>$ssc,'taxable_reduction'=>$taxReduction,'ssc_base_reduction'=>$sscReduction,'details'=>$details];}
public function markApplied(Payslip $payslip,array $details):void{if($details===[])return;DB::transaction(function()use($payslip,$details){foreach($details as $d){$updated=PayrollAdjustment::query()->whereKey($d['adjustment_id'])->where('status','approved')->whereNull('applied_payroll_run_id')->update(['status'=>'applied','applied_payroll_run_id'=>$payslip->payroll_run_id,'applied_payslip_id'=>$payslip->id,'applied_at'=>now()]);if($updated!==1)throw new RuntimeException(__('payroll.adjustment_already_consumed'));}});}
}
