<?php
namespace App\Services;
use App\Models\ComplianceSetting; use App\Models\Employee; use App\Models\EmployeeDeduction; use App\Models\EmployeeEarning; use App\Models\OvertimeEntry; use App\Support\Money; use Brick\Math\BigDecimal; use Brick\Math\RoundingMode; use Carbon\Carbon; use RuntimeException;
class PayrollEngine
{
public function __construct(private ComplianceSettingsService $compliance,private SscCalculator $ssc,private ProgressiveTaxCalculator $taxCalculator,private LoanService $loans,private AbsenceService $absences,private SalaryProrationService $proration){}
public function calculate(Employee $employee,int $month,int $year,?ComplianceSetting $setting=null):array
{
$start=Carbon::create($year,$month,1)->startOfMonth();$end=$start->copy()->endOfMonth();$record=$setting?:$this->compliance->forDate($end);$s=$record->settings;$this->compliance->require($s,['ssc_employee_percent','ssc_employer_percent','ssc_enrollment_cutoff_date','ssc_ceiling_pre_cutoff_jod','ssc_ceiling_post_cutoff_jod','income_tax_brackets','personal_exemption_annual_jod','high_earner_surcharge_threshold_annual_jod','high_earner_surcharge_percent','overtime_multiplier_standard','overtime_multiplier_rest_holiday','monthly_hours_divisor','salary_daily_divisor']);
$proration=$this->proration->calculate($employee,$start,$end,$s);$contract=Money::d($proration['contract_salary']);$scheduledBase=Money::d($proration['payable_salary']);$earning=$this->earningsForPeriod($employee,$start,$end);$deduction=$this->deductionsForPeriod($employee,$start,$end);$loan=$this->loans->dueForPeriod($employee,$start,$end);$absence=$this->absences->deductionForPeriod($employee,$start,$end,$contract,$s);$earnedBase=$scheduledBase->minus($absence['total']);if($earnedBase->isLessThan(0))$earnedBase=BigDecimal::zero();
$sscBase=$earnedBase->plus($earning['ssc_applicable'])->minus($deduction['ssc_base_reduction']);if($sscBase->isLessThan(0))$sscBase=BigDecimal::zero();$ssc=$this->ssc->calculate($sscBase,$employee->ssc_enrollment_date,$s);$ot=$this->overtimePay($employee,$month,$year,$contract);$overtime=$ot['total'];$taxable=$earnedBase->plus($overtime)->plus($earning['taxable'])->minus($ssc['employee'])->minus($deduction['taxable_reduction']);if($taxable->isLessThan(0))$taxable=BigDecimal::zero();$annualIncome=$earnedBase->plus($overtime)->plus($earning['taxable'])->multipliedBy('12');$annualTaxable=$taxable->multipliedBy('12')->minus((string)$s['personal_exemption_annual_jod']);if($annualTaxable->isLessThan(0))$annualTaxable=BigDecimal::zero();$annualTax=$this->taxCalculator->calculate($annualTaxable,$s['income_tax_brackets']);$annualSurcharge=BigDecimal::zero();$threshold=Money::d((string)$s['high_earner_surcharge_threshold_annual_jod']);if($annualIncome->isGreaterThan($threshold))$annualSurcharge=Money::percent($annualIncome->minus($threshold),(string)$s['high_earner_surcharge_percent']);$incomeTax=$annualTax->dividedBy('12',12,RoundingMode::HALF_UP);$surcharge=$annualSurcharge->dividedBy('12',12,RoundingMode::HALF_UP);$net=$earnedBase->plus($overtime)->plus($earning['total'])->minus($deduction['total'])->minus($loan['total'])->minus($ssc['employee'])->minus($incomeTax)->minus($surcharge);
return ['contract_salary'=>$proration['contract_salary'],'gross_salary'=>$proration['payable_salary'],'proration_adjustment'=>$proration['proration_adjustment'],'overtime_pay'=>Money::round($overtime),'earnings_total'=>Money::round($earning['total']),'deductions_total'=>Money::round($deduction['total']),'loan_deductions_total'=>Money::round($loan['total']),'unpaid_absence_deduction'=>Money::round($absence['total']),'ssc_employee'=>Money::round($ssc['employee']),'ssc_employer'=>Money::round($ssc['employer']),'income_tax'=>Money::round($incomeTax),'surcharge'=>Money::round($surcharge),'net_salary'=>Money::round($net),'compliance_setting_id'=>$record->id,'loan_repayments'=>$loan['details'],'snapshot'=>['setting_version'=>$record->version_label,'effective_date'=>$record->effective_date->toDateString(),'settings'=>$s,'salary_proration'=>$proration,'earned_base_salary'=>Money::round($earnedBase),'unpaid_absence_deduction'=>Money::round($absence['total']),'unpaid_absence_details'=>$absence['details'],'earnings_total'=>Money::round($earning['total']),'earnings_details'=>$earning['details'],'deductions_total'=>Money::round($deduction['total']),'deduction_details'=>$deduction['details'],'loan_deductions_total'=>Money::round($loan['total']),'loan_repayment_details'=>$loan['details'],'ssc_ceiling_used'=>Money::round($ssc['ceiling']),'ssc_base'=>Money::round($ssc['base']),'pre_cutoff_enrollment'=>$ssc['pre_cutoff'],'annual_income'=>Money::round($annualIncome),'annual_taxable'=>Money::round($annualTaxable),'overtime_details'=>$ot['details']]];
}
private function earningsForPeriod(Employee $e,Carbon $s,Carbon $end):array{$rows=EmployeeEarning::where('employee_id',$e->id)->applicableTo($s,$end)->get();$total=BigDecimal::zero();$tax=BigDecimal::zero();$ssc=BigDecimal::zero();$details=[];foreach($rows as $r){$a=Money::d($r->amount);$total=$total->plus($a);if($r->taxable)$tax=$tax->plus($a);if($r->ssc_applicable)$ssc=$ssc->plus($a);$details[]=['earning_id'=>$r->id,'category'=>$r->category,'name'=>$r->name,'amount_jod'=>Money::round($a),'taxable'=>$r->taxable,'ssc_applicable'=>$r->ssc_applicable,'recurring'=>$r->recurring];}return['total'=>$total,'taxable'=>$tax,'ssc_applicable'=>$ssc,'details'=>$details];}
private function deductionsForPeriod(Employee $e,Carbon $s,Carbon $end):array{$rows=EmployeeDeduction::where('employee_id',$e->id)->applicableTo($s,$end)->get();$total=BigDecimal::zero();$tax=BigDecimal::zero();$ssc=BigDecimal::zero();$details=[];foreach($rows as $r){$a=Money::d($r->amount);$total=$total->plus($a);if($r->reduces_taxable_income)$tax=$tax->plus($a);if($r->reduces_ssc_base)$ssc=$ssc->plus($a);$details[]=['deduction_id'=>$r->id,'category'=>$r->category,'name'=>$r->name,'amount_jod'=>Money::round($a),'reduces_taxable_income'=>$r->reduces_taxable_income,'reduces_ssc_base'=>$r->reduces_ssc_base,'recurring'=>$r->recurring];}return['total'=>$total,'taxable_reduction'=>$tax,'ssc_base_reduction'=>$ssc,'details'=>$details];}
private function overtimePay(Employee $e,int $m,int $y,BigDecimal $gross):array{$rows=OvertimeEntry::where('employee_id',$e->id)->where('status','approved')->whereYear('date',$y)->whereMonth('date',$m)->orderBy('date')->get();$total=BigDecimal::zero();$details=[];$cache=[];foreach($rows as $r){$d=$r->date->toDateString();if(!isset($cache[$d])){$c=$this->compliance->forDate($r->date);$this->compliance->require($c->settings,['monthly_hours_divisor','overtime_multiplier_standard','overtime_multiplier_rest_holiday']);$cache[$d]=$c;}$c=$cache[$d];$s=$c->settings;$div=Money::d((string)$s['monthly_hours_divisor']);if($div->isLessThanOrEqualTo(0))throw new RuntimeException('monthly_hours_divisor must be greater than zero.');$hourly=$gross->dividedBy($div,12,RoundingMode::HALF_UP);$mult=(string)$s[$r->rate_type==='rest_holiday'?'overtime_multiplier_rest_holiday':'overtime_multiplier_standard'];$pay=$hourly->multipliedBy((string)$r->hours)->multipliedBy($mult);$total=$total->plus($pay);$details[]=['entry_id'=>$r->id,'date'=>$d,'hours'=>(string)$r->hours,'rate_type'=>$r->rate_type,'multiplier'=>$mult,'monthly_hours_divisor'=>(string)$s['monthly_hours_divisor'],'settings_version'=>$c->version_label,'amount_jod'=>Money::round($pay)];}return['total'=>$total,'details'=>$details];}
}
