<?php
namespace App\Livewire\Adjustments;
use App\Models\Employee; use App\Models\PayrollAdjustment; use App\Models\PayrollRun; use App\Services\PayrollAdjustmentService; use Livewire\Component;
class Index extends Component
{
public array $form=[];public function mount():void{$this->resetForm();}
public function save():void{$this->authorize('adjustments.manage');$data=$this->validate(['form.employee_id'=>['required','exists:employees,id'],'form.kind'=>['required','in:earning,deduction'],'form.name'=>['required','string','max:255'],'form.amount'=>['required','decimal:0,3','min:0.001'],'form.payment_month'=>['required','integer','between:1,12'],'form.payment_year'=>['required','integer','between:2000,2200'],'form.target_payroll_run_id'=>['nullable','exists:payroll_runs,id'],'form.source_month'=>['nullable','integer','between:1,12'],'form.source_year'=>['nullable','integer','between:2000,2200'],'form.taxable'=>['boolean'],'form.ssc_applicable'=>['boolean'],'form.reduces_taxable_income'=>['boolean'],'form.reduces_ssc_base'=>['boolean'],'form.reason'=>['required','string','max:2000']])['form'];if(filled($data['target_payroll_run_id'])){$run=PayrollRun::findOrFail($data['target_payroll_run_id']);if(!$run->isOffCycle()||$run->status!=='draft'){$this->addError('adjustment','Target payroll must be a draft off-cycle run.');return;}$data['payment_month']=$run->month;$data['payment_year']=$run->year;if($data['taxable']||$data['ssc_applicable']||$data['reduces_taxable_income']||$data['reduces_ssc_base']){$this->addError('adjustment','Off-cycle adjustments cannot affect tax or SSC; use regular payroll.');return;}}else{$data['target_payroll_run_id']=null;}PayrollAdjustment::create($data+['status'=>'pending','created_by'=>auth()->id()]);$this->resetForm();session()->flash('success',__('hr.saved'));}
public function approve(int $id,PayrollAdjustmentService $s):void{$this->authorize('adjustments.manage');try{$s->approve(PayrollAdjustment::findOrFail($id),auth()->id());session()->flash('success',__('hr.approved'));}catch(\RuntimeException $e){$this->addError('adjustment',$e->getMessage());}}
public function void(int $id,PayrollAdjustmentService $s):void{$this->authorize('adjustments.manage');try{$s->void(PayrollAdjustment::findOrFail($id));session()->flash('success',__('hr.saved'));}catch(\RuntimeException $e){$this->addError('adjustment',$e->getMessage());}}
private function resetForm():void{$this->form=['employee_id'=>'','kind'=>'earning','name'=>'','amount'=>'','payment_month'=>(int)now()->month,'payment_year'=>(int)now()->year,'target_payroll_run_id'=>'','source_month'=>'','source_year'=>'','taxable'=>true,'ssc_applicable'=>true,'reduces_taxable_income'=>false,'reduces_ssc_base'=>false,'reason'=>''];}
public function render(){return view('livewire.adjustments.index',['employees'=>Employee::orderBy('name')->get(['id','name']),'offCycleRuns'=>PayrollRun::where('run_type','off_cycle')->where('status','draft')->orderByDesc('year')->orderByDesc('month')->orderByDesc('sequence')->get(),'rows'=>PayrollAdjustment::with(['employee','targetPayrollRun'])->latest('id')->get()]);}
}
